# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import maths_pb2 as maths__pb2


class MathsStub(object):
    """The maths service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Fibonacci = channel.unary_unary(
                '/Maths/Fibonacci',
                request_serializer=maths__pb2.FibonacciRequest.SerializeToString,
                response_deserializer=maths__pb2.FibonacciResponse.FromString,
                )
        self.Factorial = channel.unary_unary(
                '/Maths/Factorial',
                request_serializer=maths__pb2.FactorialRequest.SerializeToString,
                response_deserializer=maths__pb2.FactorialResponse.FromString,
                )
        self.Count = channel.unary_stream(
                '/Maths/Count',
                request_serializer=maths__pb2.Counter.SerializeToString,
                response_deserializer=maths__pb2.CounterResult.FromString,
                )


class MathsServicer(object):
    """The maths service definition.
    """

    def Fibonacci(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Factorial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Count(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MathsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Fibonacci': grpc.unary_unary_rpc_method_handler(
                    servicer.Fibonacci,
                    request_deserializer=maths__pb2.FibonacciRequest.FromString,
                    response_serializer=maths__pb2.FibonacciResponse.SerializeToString,
            ),
            'Factorial': grpc.unary_unary_rpc_method_handler(
                    servicer.Factorial,
                    request_deserializer=maths__pb2.FactorialRequest.FromString,
                    response_serializer=maths__pb2.FactorialResponse.SerializeToString,
            ),
            'Count': grpc.unary_stream_rpc_method_handler(
                    servicer.Count,
                    request_deserializer=maths__pb2.Counter.FromString,
                    response_serializer=maths__pb2.CounterResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Maths', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Maths(object):
    """The maths service definition.
    """

    @staticmethod
    def Fibonacci(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Maths/Fibonacci',
            maths__pb2.FibonacciRequest.SerializeToString,
            maths__pb2.FibonacciResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Factorial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Maths/Factorial',
            maths__pb2.FactorialRequest.SerializeToString,
            maths__pb2.FactorialResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Count(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Maths/Count',
            maths__pb2.Counter.SerializeToString,
            maths__pb2.CounterResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
